### ISSUE TITLE
Yyy

### ISSUE THREAD

**Issue by MTG33** [Benchamxd/Telegraph-Uploader#5]
Hhh

**Comment by Xsenix** [comment]
have mesage output


Traceback (most recent call last):
  File "C:\Users\Baka-Chan\Desktop\Telegraph-Uploader-main\bot.py", line 139, in <module>
    Tgraph.run()
  File "C:\Users\Baka-Chan\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\methods\utilities\run.py", line 84, in run
    self.start()
  File "C:\Users\Baka-Chan\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\sync.py", line 66, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Baka-Chan\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Baka-Chan\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\methods\utilities\start.py", line 58, in start
    is_authorized = await self.connect()
                    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Baka-Chan\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\methods\auth\connect.py", line 40, in connect
    await self.load_session()
  File "C:\Users\Baka-Chan\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrogram\client.py", line 602, in load_session
    raise AttributeError("The API key is required for new authorizations. "
AttributeError: The API key is required for new authorizations. More info: https://docs.pyrogram.org/start/auth
